# .streamlit/secrets.toml

# ===============================================
# MySQL Database Credentials
# The key 'mysql' matches the expected structure: st.secrets['mysql']['host']
# ===============================================

[mysql]
host = "127.0.0.1"
user = "bhargavi"
password = "cseds@32"
database = "circle"

# Note: In a real environment like Render, you must use Environment Variables 
# named MYSQL_HOST, MYSQL_USER, etc., instead of this file.
